### ISSUE TITLE
MQTT Notification raise "curl_easy_perform failed: Timeout was reached"

### ISSUE THREAD

**Issue by walterwootz** [Fiware/context.Orion-LD#1178]
Hi everyone,

I'm trying to receive Orion LD notifications using mqtt protocol which instead work well with Orion v2.

The error is the following:

```
time=Friday 08 Jul 14:42:43 2022.769Z | lvl=ERROR | corr=N/A | trans=1657291349-662-00000000001 | from=pending | srv=pending | subsrv=pending | comp=Orion | op=httpRequestSend.cpp[573]:httpRequestSendWithCurl | msg=curl_easy_perform failed: 28

time=Friday 08 Jul 14:42:43 2022.769Z | lvl=WARN | corr=N/A | trans=1657291349-662-00000000001 | from=pending | srv=pending | subsrv=pending | comp=Orion | op=AlarmManager.cpp[338]:notificationError | 
msg=Raising alarm NotificationError mqtt//mosquitto:1883/example_mosquitto_topic?subscriptionId=urn:ngsi-ld:Subscription:329e3c8e-fecc-11ec-92f9-0242c0a8500d: (curl_easy_perform failed: Timeout was reached)
```

 Orion is launched using a docker-compose together with an instance of mosquitto where mqtt notifications should be sent. Consider that the subscription using the json below is successfull.

**docker-compose.yaml**
```
   orion:
    hostname: orion
    image: fiware/orion-ld:latest
    networks:
      - hostnet
    ports:
      - "1026:1026"
    depends_on:
      - mongodb
      - mosquitto
    # add -forwarding if using NGSI-ld
    command: -statCounters -dbhost mongodb -logLevel DEBUG -forwarding
    environment:
       - IOTA_JSON_LD_CONTEXT=https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld #comment if you mind using NGSIv2

  mongodb:
    hostname: mongodb
    image: mongo:4.2
    networks:
      - hostnet
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_volume:/data/db
      - mongo_conf_volume:/data/configdb
    command: --nojournal

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    networks:
      - hostnet
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./conf/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_volume:/mosquitto/data

volumes:
  mongo_data_volume:
  mongo_conf_volume:
  mosquitto_volume:
```

**json subscription request**
```
{
  "type": "Subscription",
  "name": "Car-Subscription",
  "description": "Car subscription",
  "entities": [
    {
      "id": "urn:ngsi-ld:Device:age01_Car",
      "type": "Device"
    }
  ],
  "watchedAttributes": [
    "Engine_Oxigen",
    "Engine_Temperature"
  ],
  "notification": {
    "attributes": [
      "Engine_Oxigen",
      "Engine_Temperature"
    ],
    "format": "keyValues",
    "endpoint": {
      "uri": "mqtt://mosquitto:1883/example_mosquitto_topic"
    }
  },
  "@context": "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
}
```

The error seems to be raised on function _httpRequestSendWithCurl_ in [httpRequestSend.cpp](https://github.com/FIWARE/context.Orion-LD/blob/develop/src/lib/rest/httpRequestSend.cpp) (it's just a guess, no debugging has been done). Maybe the url is not recognized correctly as mqtt? Or something is wrong on the subscription request object?

Thank you!
