### ISSUE TITLE
attributes subscription option gets ignored when entity was created via entityOperations/create endpoint

### ISSUE THREAD

**Issue by Blobonat** [Fiware/context.Orion-LD#1244]
I already created a detailed [issue for the Scorpio Context Broker](https://github.com/ScorpioBroker/ScorpioBroker/issues/337) (please have a look for the steps to reproduce the bug (?))

When creating a subscription for an entity, which was created via the `entityOperations/create` endpoint the selected attributes for the subscription via `attributes` get ignored and only the attributes that were actually updated are included in the notification.

Tested version: 
```
orion:
    image: fiware/orion-ld:1.1.1
    depends_on:
      - mongodb
      - mintaka
    ports:
      - "1026:1026"
    command: -experimental -dbhost mongodb
    environment:
      - ORIONLD_TROE=TRUE
      - ORIONLD_TROE_USER=orion
      - ORIONLD_TROE_PWD=orion
      - ORIONLD_TROE_HOST=timescale
      - ORIONLD_MONGO_HOST=mongo-db
```

Since both Orion-LD and Scorpio have the same (from my point of view inconsistent) behavior, maybe I have missed something in the NGSI-LD API spec?
