### ISSUE TITLE
Issue with Mongo Cluster

### ISSUE THREAD

**Issue by sjerman** [Fiware/context.Orion-LD#1338]
Hi, here is the first issue.

I am testing against a MongoDB cluster/replicaset, with the following env variables:

```
      containers:
        - name: orion
          image: fiware/orion-ld:1.1.2
          ports:
            - name: http
              containerPort: 1026
              protocol: TCP
          env:
            - name: ORIONLD_EXPERIMENTAL
              value: 'TRUE'
            - name: ORIONLD_MONGO_HOST
              value: >-
                kloudspot-mongodb-0.kloudspot-mongodb-headless:27017,kloudspot-mongodb-1.kloudspot-mongodb-headless:27017,kloudspot-mongodb-2.kloudspot-mongodb-headless:27017
            - name: ORIONLD_MONGO_DB
              value: orionld
            - name: ORIONLD_MONGO_USER
              value: root
            - name: ORIONLD_MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kloudspot-secret
                  key: mongodb-root-password
            - name: ORIONLD_MONGO_AUTH_MECH
              value: SCRAM-SHA-1
            - name: ORIONLD_LOG_LEVEL
              value: WARN
            - name: ORIONLD_TROE
              value: 'FALSE'
```
I am getting the following error:

```
time=Thursday 16 Mar 09:44:35 2023.078Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongocInit.cpp[277]:mongocInit | msg=Connecting to mongo using the C driver (mongoc)
time=Thursday 16 Mar 09:44:35 2023.100Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[320]:mongoConnectionPoolInit | msg=Connecting to mongo for the C++ legacy driver
terminate called after throwing an instance of 'mongo::UserException'
  what():  More than one ':' detected. If this is an ipv6 address, it needs to be surrounded by '[' and ']'; kloudspot-mongodb-0.kloudspot-mongodb-headless:27017,kloudspot-mongodb-1.kloudspot-mongodb-headless:27017,kloudspot-mongodb-2.kloudspot-mongodb-headless:27017
```

Note that this works if I add ORIONLD_MONGOCONLY
