### ISSUE TITLE
High resource usage while starting Orion-LD

### ISSUE THREAD

**Issue by ttutuncu** [Fiware/context.Orion-LD#1418]
Hi,

We have a problem with our Orion-LD instance which when starting up it uses a high amount of CPU and RAM. What can cause this issue, is this normal? It usually exausts the RAM and causes an oomkilled.

We use it on a 2CPU 10GB RAM server and it exceeds these resources and it takes around 26 minutes to startup, sometimes failing with oomkilled. When it starts up it releases the memory to around 4-5GB. Something is happening between the "Connecting to mongo using the C driver (mongoc)" state and "Initialization ready - accepting REST requests on port 1026" state. I have shared the console log below. Is there any detailed log I can check and share with you?

```
time=2023-08-29T11:59:57.778Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionld.cpp[737]:versionInfo | msg=Version Info:
time=2023-08-29T11:59:57.778Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionld.cpp[738]:versionInfo | msg=-----------------------------------------
time=2023-08-29T11:59:57.778Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionld.cpp[739]:versionInfo | msg=orionld version: 1.1.2
time=2023-08-29T11:59:57.778Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionld.cpp[740]:versionInfo | msg=based on orion: 1.15.0-next
time=2023-08-29T11:59:57.778Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionld.cpp[741]:versionInfo | msg=git hash: nogitversion
time=2023-08-29T11:59:57.778Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionld.cpp[742]:versionInfo | msg=build branch: 
time=2023-08-29T11:59:57.778Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionld.cpp[743]:versionInfo | msg=compiled by: root
time=2023-08-29T11:59:57.778Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionld.cpp[744]:versionInfo | msg=compiled in: 
time=2023-08-29T11:59:57.778Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionld.cpp[745]:versionInfo | msg=-----------------------------------------
NOTICE: extension "postgis" already exists, skipping
time=2023-08-29T11:59:57.838Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongocInit.cpp[277]:mongocInit | msg=Connecting to mongo using the C driver (mongoc)
NOTICE: extension "postgis" already exists, skipping
time=2023-08-29T12:08:05.287Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[320]:mongoConnectionPoolInit | msg=Connecting to mongo for the C++ legacy driver
time=2023-08-29T12:25:54.344Z | lvl=TMP | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionld.cpp[1169]:main | msg=Initialization ready - accepting REST requests on port 1026 (experimental API endpoints are disabled)
```

Orion-LD: v1.1.2 (tried with 1.4 latest release using the same DB, same situation)
MongoDB: v 3.6.23-13.0

Really appreciate your help,
Thanks.

**Comment by kzangeli** [comment]
That is very weird.
We start Orion-LD on one core and 4-5 Gb of RAM and it serves 5000 GETs per second without a problem.
It starts in a few milliseconds.

So, something is definitely off here ...
Please start your broker with ALL traces on and see if that helps us to understand what's happening:

`orionld -logLevel DEBUG -t 0-255` (plus any parameters you're using)

Post the traces right here and I'll have a look

**Comment by ttutuncu** [comment]
Hi Ken,
Thank you for your quick response. 
We opened the debug trace but we are not recieving any Debug logs into the console. Our deployment file is as follows:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-ld-cb
  namespace: fiware-new
  labels:
    app: orion-ld-cb
spec:
  replicas: 0
  selector:
    matchLabels:
      app: orion-ld-cb
  template:
    metadata:
      labels:
        app: orion-ld-cb
    spec:
      containers:
        - name: orion-ld-cb
          image: fiware/orion-ld:1.1.2
          ports:
            - containerPort: 1026
              protocol: TCP
          env:
            - name: ORIONLD_TROE
              value: 'TRUE'
            - name: ORIONLD_TROE_USER
              value: postgres
            - name: ORIONLD_TROE_PWD
              value: CM***************Zh6C
            - name: ORIONLD_TROE_HOST
              value: 192.168.40.115
            - name: ORIONLD_MULTI_SERVICE
              value: 'TRUE'
            - name: ORIONLD_DISABLE_FILE_LOG
              value: 'TRUE'
            - name: ORIONLD_TROE_POOL_SIZE
              value: '100'
            - name: ORIONLD_MONGO_HOST
              value: 192.168.40.110:27017,192.168.40.111:27017,192.168.40.113:27017
            - name: ORIONLD_MONGO_DB
              value: orion
            - name: ORIONLD_MONGO_REPLICA_SET
              value: rs0
            - name: ORIONLD_MONGO_USER
              value: default-admin
            - name: ORIONLD_MONGO_PASSWORD
              value: Sp****************jsY
            - name: ORIONLD_MONGO_AUTH_SOURCE
              value: admin
            - name: ORIONLD_LOG_LEVEL
              value: DEBUG
            - name: ORIONLD_TRACE
              value: 0-255
```

Why are we not seeing any debug logs? Is there anything else we can try?

Thanks.
