### ISSUE TITLE
Short Time History: Persistence as compound vs. numeric values

### ISSUE THREAD

**Issue by IngMiad** [Fiware/context.Orion-LD#1651]
Hello @kzangeli,

I have another question regarding short term history: **When is an attribute saved as compound value and when as dedicated number / boolean / ... in the database?**

The background is that I have two different OPC UA real-life datasources that are read via IoT-Agent OPC UA and provided to Orion-LD. Orion-LD persists the data from the two sources in different ways:
1. The first data source is a weather station which uses the WeatherObserved data model (see here: https://raw.githubusercontent.com/smart-data-models/dataModel.Weather/master/WeatherObserved/model.yaml#/WeatherObserved). This data is persisted as numeric values in the time-series-database as expected.
2. The other is a process control system which uses a self-made data model. This data is persisted as compound values in the database for boolean and numeric values. I would also expect that this data is persisted as numeric / boolean values in the time-series-database just like the first WeatherObserved entity.

When I have a look at the data models I don't understand why data from the first source is persisted in a different way compared to data from the second source. Here is a direct example for two different attributes that are persisted as a number in case of the WeatherObserved entity and as a compound value in the case of the process control system:
```
    # FROM FIRST DATASOURCE
	WeatherObserved:
      description: "Weather conditions"     
      properties:
        windSpeed:
          description: Intensity of the wind
          minimum: 0
          type: number
          x-ngsi:
            model: http//schema.org/Number
            type: Property  
		...

	# FROM SECOND DATASOURCE
    TurbineBearing:
      description: "Process management system component 'Turbine bearing'"
      properties:
        0MAD10CT001_Temp_Lager_P84_1_U:
          description: "0MAD10CT001/Temp_Lager_P84_1.U: Turbine bearing Nr. 10 Measuring circuit Temperature Nr. 001  (Analog value measurement)"
          type: "number"
          x-ngsi:
            model: "https://schema.org/Number"
            type: "Property"
		...
```
Both data models use a property name, description, type and x-ngsi-model and x-ngsi-type - the first is using a minimum additionally, but this is not true for alle WeatherObserved attributes. 

Here is a full example of both entity models for further reference:
```
    #####################
    ## WeatherObserved ##
    #####################
    # FROM FIRST DATASOURCE
	WeatherObserved:
      description: "Weather conditions"
      required:
        - id
        - type
        #- dateObserved
        #- location      
      properties:
        atmosphericPressure:
          description: The atmospheric pressure observed measured in Hecto Pascals
          minimum: 0
          type: number
          x-ngsi:
            model: https://schema.org/Number
            type: Property
            units: Hecto pascals
        diffuseIrradiation:
          description: Diffuse irradiance is the part of the solar irradiance that is scattered by the atmosphere
          minimum: 0
          type: number
          x-ngsi:
            model: https://schema.org/Number
            type: Property
            units: w/m2
        directIrradiation:
          description: Direct irradiance is the part of the solar irradiance that directly reaches a surface
          minimum: 0
          type: number
          x-ngsi:
            model: https://schema.org/Number
            type: Property
            units: w/m2
        id:
          anyOf:
            - description: Identifier format of any NGSI entity
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
              x-ngsi:
                type: Property
            - description: Identifier format of any NGSI entity
              format: uri
              type: string
              x-ngsi:
                type: Property
          description: Unique identifier of the entity
          x-ngsi:
            type: Property
        precipitation:
          description: 'Amount of water rain registered. '
          minimum: 0
          type: number
          x-ngsi:
            model: https://schema.org/Number
            type: Property
            units: Liters per square meter
        refDevice:
          anyOf:
            - description: Identifier format of any NGSI entity
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
              x-ngsi:
                type: Property
            - description: Identifier format of any NGSI entity
              format: uri
              type: string
              x-ngsi:
                type: Property
          description: A reference to the device(s) which captured this observation
          x-ngsi:
            model: https://schema.org/URL
            type: Relationship
        relativeHumidity:
          description: Humidity in the Air. Observed instantaneous relative humidity (water vapour in air)
          maximum: 1
          minimum: 0
          type: number
          x-ngsi:
            type: Property
        solarRadiation:
          description: The solar radiation observed measured in Watts per square
          minimum: 0
          type: number
          x-ngsi:
            model: https://schema.org/Number
            type: Property
            units: w/m2
        temperature:
          description: Temperature of the item
          type: number
          x-ngsi:
            type: Property
        type:
          description: NGSI Entity type. It has to be WeatherObserved
          enum:
            - WeatherObserved
          type: string
          x-ngsi:
            type: Property
        windDirection:
          description: Direction of the wind bet
          maximum: 360
          minimum: 0
          type: number
          x-ngsi:
            model: http://schema.org/Number
            type: Property
        windSpeed:
          description: Intensity of the wind
          minimum: 0
          type: number
          x-ngsi:
            model: http//schema.org/Number
            type: Property     


    ####################
    ## TurbineBearing ##
    ####################
	# FROM SECOND DATASOURCE
    TurbineBearing:
      description: "Process management system function 'Turbine bearing' with KKS function code: 'MAD' (de: 'Turbinenlagerung')"
      required:
        - "id"
        - "type"
        - "dateObserved"
        - "isPartOf"
      properties:
        id:
          anyOf:
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
              type: "string"
            - description: "Property. Identifier format of any NGSI entity"
              format: "uri"
              type: "string"
          description: "Unique identifier of the entity"
          x-ngsi:
            type: "Property"
        type:
          description: "NGSI Entity type. It has to be 'TurbineBearing' (a specific PCS part)"
          enum:
            - "TurbineBearing"
          type: "string"
          x-ngsi:
            type: "Property"
        dateObserved:
          description: "Date of the observed entity defined by the user."
          type: "string"
          x-ngsi:
            type: "Property"
        isPartOf:
          description: "This component is a sub component of another system"
          type: "string"
          x-ngsi:
            model: "https://schema.org/isPartOf"
            type: "Relationship"
        kksFunction:
          description: "KKS function of property (level 1)"
          type: "string"
          x-ngsi:
            type: "Property"
        0MAD10CT007_Temp_Lager_P84_7_U:
          description: "0MAD10CT007/Temp_Lager_P84_7.U: Turbine bearing Nr. 10 Measuring circuit Temperature Nr. 007  (Analog value measurement)"
          type: "number"
          x-ngsi:
            model: "https://schema.org/Number"
            type: "Property"
        0MAD10CT007_Temp_Lager_P84_7_VSTATUS:
          description: "0MAD10CT007/Temp_Lager_P84_7.VSTATUS: Turbine bearing Nr. 10 Measuring circuit Temperature Nr. 007  (VSTATUS)"
          type: "boolean"
          x-ngsi:
            model: "https://schema.org/Boolean"
            type: "Property"
        0MAD10CT008_Temp_Lager_P84_8_U:
          description: "0MAD10CT008/Temp_Lager_P84_8.U: Turbine bearing Nr. 10 Measuring circuit Temperature Nr. 008  (Analog value measurement)"
          type: "number"
          x-ngsi:
            model: "https://schema.org/Number"
            type: "Property"
        0MAD10CT008_Temp_Lager_P84_8_VSTATUS:
          description: "0MAD10CT008/Temp_Lager_P84_8.VSTATUS: Turbine bearing Nr. 10 Measuring circuit Temperature Nr. 008  (VSTATUS)"
          type: "boolean"
          x-ngsi:
            model: "https://schema.org/Boolean"
            type: "Property"
        0MAD10CT001_Temp_Lager_P84_1_U:
          description: "0MAD10CT001/Temp_Lager_P84_1.U: Turbine bearing Nr. 10 Measuring circuit Temperature Nr. 001  (Analog value measurement)"
          type: "number"
          x-ngsi:
            model: "https://schema.org/Number"
            type: "Property"
		...
```
