### ISSUE TITLE
orion-ld disable TMP logs

### ISSUE THREAD

**Issue by damianhorna** [Fiware/context.Orion-LD#920]
Hi, 

I am running orion-ld with the docker-compose like this:
```
version: "3.9"
services:
  mongo:
    image: mongo:3.6
    command: --nojournal
  orion:
      image: fiware/orion-ld
      links:
        - mongo
      ports:
        - "1026:1026"
      command: -dbhost mongo
```

Is it possible to specify within the docker-compose.yml file what should be the logging level for orion-ld? Right now it generates a ton of TMP logging messages like this:
```
Thursday 19 Aug 12:09:04 2021.777Z | lvl=TMP | corr=N/A | trans=1629374772-423-00000002725 | from=pending | srv=pending | subsrv=pending | comp=Orion | op=httpRequestSend.cpp[547]:httpRequestSendWithCurl | msg=Sending message 2716 to HTTP server: sending message of 691 bytes to HTTP server
```

and I don't really need to have the orion log every time it sends a notification. Any help would be much appreciated!
